/**
 * AI Architect panel.
 *
 * A conversation about one design, not a general chat window. Every answer
 * carries the engines that produced it, so a reader can always tell a fact
 * about their architecture from a model's general knowledge — which is the
 * distinction the whole feature rests on.
 *
 * The panel holds no design state of its own. It sends the prompt with each
 * question and the backend regenerates deterministically, so the answer is
 * always about the architecture currently on screen.
 */

import { api } from "./api.js";
import { clear, copyText, el, icon, toast } from "./ui.js";

/** Source name → how it should read as a badge. */
const SOURCE_STYLE = {
  "InfrastructureSpec": "brand",
  "Decision Trace": "brand",
  "Explainability Layer": "brand",
  "Optimization Engine": "info",
  "Validation Engine": "warning",
  "Cost Estimator": "success",
  "Terraform Generator": "neutral",
};

/**
 * Render a small subset of markdown as elements.
 *
 * Only **bold**, `code` and bullet lines, because that is all the architect
 * emits. Built as nodes rather than parsed into HTML: the text quotes user
 * prompts and resource ids, and an innerHTML shortcut here would be an
 * injection the moment a prompt contained markup.
 */
function renderText(text, onResourceClick, knownResources) {
  const container = el("div", { class: "chat__text" });

  for (const rawLine of text.split("\n")) {
    const line = rawLine.trimEnd();

    if (!line) {
      container.append(el("div", { class: "chat__gap" }));
      continue;
    }
    if (line === "---") {
      container.append(el("hr", { class: "chat__rule" }));
      continue;
    }

    const isBullet = line.startsWith("• ");
    const body = isBullet ? line.slice(2) : line;
    const node = el("p", { class: isBullet ? "chat__bullet" : "chat__line" });

    // One pass over **bold** and `code`, so neither can swallow the other.
    const pattern = /(\*\*[^*]+\*\*|`[^`]+`)/g;
    let cursor = 0;
    let match;
    while ((match = pattern.exec(body)) !== null) {
      if (match.index > cursor) {
        node.append(document.createTextNode(body.slice(cursor, match.index)));
      }
      const token = match[0];
      if (token.startsWith("**")) {
        node.append(el("strong", { text: token.slice(2, -2) }));
      } else {
        const value = token.slice(1, -1);
        // A code span that names a resource becomes a link to it.
        if (knownResources.has(value)) {
          node.append(el("button", {
            class: "chat__resource",
            type: "button",
            title: `Open ${value} in the inspector`,
            onClick: () => onResourceClick?.(value),
          }, [el("code", { text: value })]));
        } else {
          node.append(el("code", { text: value }));
        }
      }
      cursor = match.index + token.length;
    }
    if (cursor < body.length) {
      node.append(document.createTextNode(body.slice(cursor)));
    }
    container.append(node);
  }
  return container;
}

function sourceBadges(sources, deterministic) {
  if (!sources.length) {
    return el("div", { class: "chat__sources" }, [
      el("span", { class: "badge badge--neutral", text: "No source" }),
    ]);
  }
  return el("div", { class: "chat__sources" }, [
    el("span", {
      class: "chat__sources-label",
      text: deterministic ? "Answered from" : "Generated by",
    }),
    ...sources.map((source) =>
      el("span", {
        class: `badge badge--${SOURCE_STYLE[source] || "warning"}`,
        text: source,
      }),
    ),
  ]);
}

export function renderArchitect(result, ctx = {}) {
  const prompt = result.spec.prompt;
  const known = new Set(result.spec.resources.map((r) => r.id));
  const thread = el("div", { class: "chat__thread", role: "log", "aria-live": "polite" });
  const history = [];
  let busy = false;

  const input = el("input", {
    class: "field",
    type: "text",
    placeholder: "Ask why a resource exists, how to reduce cost, how two services compare…",
    "aria-label": "Ask about this architecture",
    autocomplete: "off",
  });

  const sendButton = el("button", {
    class: "btn btn--primary",
    type: "submit",
    "aria-label": "Send question",
  }, [icon("sparkles", 14), el("span", { text: "Ask" })]);

  const form = el("form", {
    class: "chat__composer",
    onSubmit: (event) => {
      event.preventDefault();
      submit(input.value);
    },
  }, [input, sendButton]);

  const suggestionRow = el("div", { class: "chat__suggestions" });

  function paintSuggestions(questions) {
    clear(suggestionRow);
    for (const question of questions) {
      suggestionRow.append(
        el("button", {
          class: "chip",
          type: "button",
          onClick: () => submit(question),
        }, [icon("sparkles", 12), el("span", { text: question })]),
      );
    }
  }

  function addQuestion(text) {
    thread.append(
      el("div", { class: "chat__turn chat__turn--asked" }, [
        el("div", { class: "chat__bubble chat__bubble--asked", text }),
      ]),
    );
  }

  function addPending() {
    const node = el("div", { class: "chat__turn" }, [
      el("div", { class: "chat__bubble chat__bubble--pending" }, [
        el("span", { class: "btn__spinner" }),
        el("span", { text: "Reading the design…" }),
      ]),
    ]);
    thread.append(node);
    thread.scrollTop = thread.scrollHeight;
    return node;
  }

  function addAnswer(answer) {
    const details = el("div", { class: "chat__details", hidden: true });
    let built = false;

    const bubble = el("div", { class: "chat__bubble chat__bubble--answer" }, [
      renderText(answer.text, ctx.onSelectResource, known),

      answer.code && el("pre", { class: "code code--boxed chat__code" }, [
        el("code", { text: answer.code }),
      ]),

      sourceBadges(answer.sources, answer.deterministic),

      el("div", { class: "chat__actions" }, [
        el("button", {
          class: "btn btn--ghost btn--sm",
          type: "button",
          onClick: () => copyText(answer.text, "Answer copied"),
        }, [icon("copy", 13), el("span", { text: "Copy" })]),

        (answer.recommendations.length > 0 || answer.findings.length > 0) &&
          el("button", {
            class: "btn btn--ghost btn--sm",
            type: "button",
            "aria-expanded": "false",
            onClick: (event) => {
              const open = details.hidden;
              if (open && !built) {
                built = true;
                details.append(buildDetails(answer, ctx));
              }
              details.hidden = !open;
              event.currentTarget.setAttribute("aria-expanded", String(open));
            },
          }, [
            icon("layers", 13),
            el("span", {
              text: answer.recommendations.length
                ? `${answer.recommendations.length} recommendation${answer.recommendations.length === 1 ? "" : "s"}`
                : `${answer.findings.length} finding${answer.findings.length === 1 ? "" : "s"}`,
            }),
          ]),

        !answer.deterministic && el("span", {
          class: "chat__warn",
          text: "Model-generated — verify before acting",
        }),
      ]),

      details,
    ]);

    thread.append(el("div", { class: "chat__turn" }, [bubble]));
    thread.scrollTop = thread.scrollHeight;
  }

  /** Recommendations arrive with their numbers, so they are shown as data. */
  function buildDetails(answer, context) {
    const rows = [];

    for (const item of answer.recommendations) {
      const delta = item.monthly_delta_usd;
      rows.push(
        el("div", { class: `opt-card opt-card--${item.priority}` }, [
          el("div", { class: "opt-card__head", style: { cursor: "default" } }, [
            el("span", { class: "opt-card__title", text: item.title }),
            el("span", {
              class: `opt-card__delta${delta < 0 ? " is-saving" : delta === 0 ? " is-free" : ""}`,
              text: delta === 0
                ? "no cost"
                : `${delta < 0 ? "−" : "+"}$${Math.abs(delta).toFixed(2)}/mo`,
            }),
          ]),
          el("div", { class: "chat__rec-meta" }, [
            el("span", { class: `badge badge--${
              item.priority === "critical" ? "error"
              : item.priority === "high" ? "warning"
              : item.priority === "medium" ? "info" : "neutral"}`, text: item.priority }),
            el("span", { class: "badge badge--neutral", text: item.difficulty }),
            ...item.resources.map((id) =>
              el("button", {
                class: "dep-chip dep-chip--action",
                type: "button",
                onClick: () => context.onSelectResource?.(id),
              }, [el("span", { text: id })]),
            ),
          ]),
          el("p", { class: "chat__rec-reason", text: item.reason }),
          el("p", { class: "chat__rec-action", text: `→ ${item.action}` }),
        ]),
      );
    }

    for (const finding of answer.findings) {
      rows.push(
        el("div", { class: `finding finding--${finding.severity}` }, [
          el("span", { class: `dot dot--${finding.severity}` }),
          el("div", { class: "finding__body" }, [
            el("p", { class: "finding__message", text: finding.message }),
            el("div", { class: "finding__meta" }, [el("code", { text: finding.code })]),
          ]),
        ]),
      );
    }

    return el("div", { class: "stack stack--tight" }, rows);
  }

  async function submit(question) {
    question = (question || "").trim();
    if (!question || busy) return;

    busy = true;
    input.value = "";
    sendButton.disabled = true;
    addQuestion(question);
    const pending = addPending();

    try {
      const answer = await api.ask(prompt, question);
      pending.remove();
      addAnswer(answer);
      history.push({ question, answer });
      if (answer.follow_ups?.length) paintSuggestions(answer.follow_ups);
    } catch (error) {
      pending.remove();
      thread.append(
        el("div", { class: "chat__turn" }, [
          el("div", { class: "chat__bubble chat__bubble--error" }, [
            icon("alert", 14),
            el("span", { text: error.message }),
          ]),
        ]),
      );
      toast("Could not answer", { message: error.message, variant: "error" });
    } finally {
      busy = false;
      sendButton.disabled = false;
      input.focus();
      thread.scrollTop = thread.scrollHeight;
    }
  }

  // Opening state: what this can do, and what it will not do.
  thread.append(
    el("div", { class: "chat__intro" }, [
      el("div", { class: "chat__intro-icon" }, [icon("sparkles", 20)]),
      el("h3", { text: "Ask about this architecture" }),
      el("p", {
        text: "Answers come from the generated design itself — the policy rules "
            + "that added each resource, the validation findings, the cost model "
            + "and the optimiser. Every reply says which engine produced it.",
      }),
      el("p", { class: "chat__intro-note" }, [
        icon("shield", 13),
        el("span", {
          text: "This assistant explains and recommends. It never changes the "
              + "design, and never adds a resource to it.",
        }),
      ]),
    ]),
  );

  paintSuggestions(result.suggestions || []);

  return el("div", { class: "chat" }, [thread, suggestionRow, form]);
}
